### ISSUE TITLE
cyg-get fails when cygwin32 and cygwin64 are both installed

### ISSUE THREAD

**Issue by mnuzzolilo** [chocolatey/chocolatey-coreteampackages#104]
Traced the issue to cyg-get.ps1, the line below creates an array of two paths when both are found

```
    $cygRoot = @($local_key, $local_key6432) | ?{Test-Path $_} | Get-ItemProperty | Select-Object -ExpandProperty rootdir
```

Then the line here combines the paths for the 32 and 64 bit installations.  

```
$cygwinsetup = "$cygRoot\cygwinsetup.exe"
```

**Comment by majkinetor** [comment]
Doesn't look it is designed to be used with both. You would need additional parameter also to designate which cygwin will get updated etc.

**Comment by mnuzzolilo** [comment]
Not even going to say what that parameter is? 11 months later? Okay.

**Comment by majkinetor** [comment]
There is no such parameter. I just say that its not designed for that and it would need a bit of care before it can handle it. Given that such functionality probably isn't of interest to many useres it doesn't substantiate work. We do accept PRs however.

**Comment by mnuzzolilo** [comment]
I would think that having cygwin32 and cygwin 64 installed but having a cryptic and unproductive error condition for such a common use case, is not such an uncommon thing. But you know best apparently.  Glad to hear that you accept PRs but I don't work for free so maybe someone else would get to it.

**Comment by mnuzzolilo** [comment]
At least now I know why so many other projects that rely on cygwin end up dropping support completely.

**Comment by majkinetor** [comment]
Dude.... what are you talking about?! This is not even a part of cygwin. Its a script that you can change your self in minutes.

**Comment by mnuzzolilo** [comment]
Now I remember why*

If someone reports a defect, which this clearly is, and is even nice enough to show exactly where it is, so the core team can more efficiently fix it, all of the benefit from doing so is completely lost when your response is to tell the requester to fix it themselves.

1) The requestor, 11 months after the fact,  no longer has a staked interest in improving the defect, as they are guaranteed to have found a workaround by then. 

2) The defect is affecting other users, as clearly stated in the issue that this occurs when multiple cygwin instances are present on the machine.  Cygwin was designed to allow this, it wasn't a coincidence that the static file data is portable (no registry, appdata, etc)...

3) The project maintainer knows the source code and architecture of the project better than someone who is submitting a bug report.  Asking them to "submit a PR" shows both lack of commitment to your project and therefore less likely for others to want to contribute to it. And it is more likely to create new bugs or maintainability problems as a PR contributor doesn't understand the architecture well enough to keep things consistent.  

Again, this is why cygwin support is poor. Because that project suffers from poor enthusiasm just as this one does.  

Trying to help you out here. Your job only gets harder when you respond like this because nobody is going to want to help. Reciprocity principle and all that.

**Comment by gep13** [comment]
>@mnuzzolilo said...
Your job only gets harder 

You refer to this as though this is a **job**, i.e. something that we are getting paid for, but let's be clear...

We aren't!

We welcome all contributions to this repository.  Not all the community maintainers in this repository are familiar with the intricate inner workings of each and every single package, and we rely on other community members to help out on packages that they have an expertise in.

Granted, this model isn't perfect, but it is what we have available to us for now.

**Comment by mnuzzolilo** [comment]
Jobs can be unpaid, and I already knew that it was unpaid.  That doesn't change the point I was making, in fact it reinforces it. If you are working for free, it's in your best interest to make it as easy on yourself as possible.  

Fair enough that there aren't anyone available who knows the package well. Would it be beneficial to have a list of packages and compenents with an active subject-matter-expert who knows the package well enough to efficiently maintain it? If such a person is available for a given module, it's good for a project to try to have them maintain that code. If no such person exists, it's good for a project to clearly label it as such so someone can be expect to have to submit a PR from the beginning. I might have been able to submit one back then had I known. I definitely cannot now that I don't even remember how this issue affected me, or where the code was, or even whether the version of the project changed.

**Comment by gep13** [comment]
>@mnuzzolilo said...
If no such person exists, it's good for a project to clearly label it as such so someone can be expect to have to submit a PR from the beginning.

I think we have to fundamentally disagree on this point.  

This is an Open Source initiative, run by people in their own time, working around things like family and work commitments.  There can be, and will not be (at least while I am involved in the project), any **expectations** placed on any maintainer of this repository, and as a result, people making use of the packages contained within this repo can't **expect** that an issue that they raise is going to get fixed.

The expectation should always be if you have found an issue, and are able to fix it, then that is the route that should be taken, as it is the most expedient way to get it corrected. 

Raising an issue, as you did here, and **expecting** that someone is going to fix it on your behalf, when you make statements like this:

>@mnuzzolilo said...
Glad to hear that you accept PRs but I don't work for free so maybe someone else would get to it.

Simply isn't going to fly.

**Comment by mnuzzolilo** [comment]
This has nothing to do with me. This was 11 months ago, I'm completely over and done with this bug. So when you talk about this as if I'm making this about me, you're completely mising the point.  This is very much about you, and your project"s success. If you want to respond that way, it's only hurting you, not me.

My comments were suggestions on how to make your project better for the community, but instead you decided to turn it into a pissing match.  That's the surest way to come out a guaranteed loser if you do that from the context of a project maintainer.  Your ego may be inflated from it but you're guaranteed to provide <= 0 net value to the project by doing so, and the guy you're arguing with loses nothing.

**Comment by mnuzzolilo** [comment]
I'd be happy to accept this philosophy of yours if you can point me to a well-cited essay or publication that establishes this as a better way to run an open source project.

**Comment by patriksvensson** [comment]
@mnuzzolilo I don't get it. You have no problem **demanding** support for software you use for free, but you're agitated when someone proposes that you help out? Why would they fix your problem for free? With that attitude I would say it's time to start paying the maintainers if you want something fixed...

**Comment by majkinetor** [comment]
Flame war, I like that !!!

>If you are working for free, it's in your best interest to make it as easy on yourself as possible.

We are already doing just that - its easiest for us just to not do anything about it for the reasons already said.

> Fair enough that there aren't anyone available who knows the package well

No, in fact, I know **exactly** what needs to be done here. I don't want to do it. Your problem is not big enough so that we need to loose hours doing it. There are more prompt issues BEFORE this one. Priority is a concept you will have to adopt. 

> I'd be happy to accept this philosophy of yours if you can point me to a well-cited essay or publication that establishes this as a better way to run an open source project.

[Nonsence](https://en.wikipedia.org/wiki/Argument_from_authority)

> If you want to respond that way, it's only hurting you, not me.

I am perfectly fine with it 'hurting me'. I don't use cygwin myself, its a kinda outated technology now.

> My comments were suggestions on how to make your project better for the community, but instead you decided to turn it into a pissing match

You are describing your own behavior here. You even said you don't care, I can only imagine what kind of pissing match would be if you cared

> Glad to hear that you accept PRs but I don't work for free so maybe someone else would get to it.

**And this is the gist here**. This sentence describes you as a person and it if it ever existed any chance of us fixing this because you want it, now it certainly doesn't, and it never will. You may learn , eventually, how to behave on open source projects (no PUBMED reference, sorry).

I don't work for free either. That is, I work for free on stuff I want, not on stuff you want. If you want it fixed so bad, and I don't, and YOU request MY time, we can always arrange something if you know what I mean :)

**Comment by majkinetor** [comment]
Furtheremore, you don't even have to use cyg-get, everything it does is achievable via `cinst cygwin -ia ...` or directkly calling its package manager. Perhaps its time to learn a bit of tool u are usuing.

**Comment by mnuzzolilo** [comment]
http://rationalwiki.org/wiki/Fallacy_fallacy Furthermore I did nothing fallacious because I wasn't arguing but rather asking for a cited source, so I could change my own beliefs. I prefer established research before setting policy, not policy-based evidencing.

Again, the red flag is that after repeated statements to the contrary, and the obvious 11 month timestamp, you all still think that I care about this bug.  My main goal here is to assess the quality of the project governance, to see how you hold up to criticism and such.  Hell, two of the committers don't even seem to agree on who knows how to maintain the project, but that detail doesn't matter because if someone is criticizing you,  they must be wrong.  Your assessments of me are invalid since you didn't understand my motives even after repeated explanations, so I'm not sure why you think you can go six steps further and sum me up as a person.

**Comment by ScottIsAFool** [comment]
"My main goal here is to assess the quality of the project governance, to see how you hold up to criticism and such."

For what purpose?

**Comment by mnuzzolilo** [comment]
Two reasons:
Learning what works and what doesn't work, for my own project management purposes

Learning how various projects are managed, to eventually be able to more easily predict whether management is a bottleneck for a given project.

**Comment by mnuzzolilo** [comment]
Sorry to waste your time, you've been helpful though

**Comment by ScottIsAFool** [comment]
Tip, this doesn't work: "I don't work for free so maybe someone else would get to it." :) hope that helps :)

**Comment by mnuzzolilo** [comment]
Tip: that statement was intended to get people's attention. It cleary worked as intended.

**Comment by majkinetor** [comment]
I can't wait for your next big project with all this great insights you got from this conversation. :)

> Sorry to waste your time

No need to appoligize. You have every right to express your opinion, and we have every right to be against it.

**Comment by ScottIsAFool** [comment]
Ahhh, so the comments and language used was all part of a social experiment. Gotcha.

**Comment by ghuntley** [comment]
@mnuzzolilo 

![](https://media.giphy.com/media/mHODom2uElPUc/giphy.gif)

Cool story bro.

**Comment by ferventcoder** [comment]
@mnuzzolilo apologies you waited 11 months to hear back. The packages in this repo are maintained by over 10 folks so sometimes there is a tragedy of the commons, which it looks like you hit here.

@majkinetor is newer and has been going through and triaging older issues with these packages, and doing a terrific job of helping us get back on track here along with @AdmiringWorm. I do feel if you had opened this issue in the last month you would have received a prompt response.

I know there may be a misunderstanding on this repo based on the name but it is meant to be a repo where folks can put packages for the community package repository and @gep13 and I had differing opinions on what that should be at first, thus the confusion in the name versus the purpose. @gep13 convinced me otherwise.

Given this issue was filed so long ago I totally get your frustration, but it does not excuse your comments here. We work on mutual respect for folks, and when it is not reciprocated it can cause issues. The Chocolatey projects have a very simple etiquette guideline - https://github.com/chocolatey/choco/blob/master/README.md#etiquette-regarding-communication

**Comment by ghuntley** [comment]
<3 the etiquette section. Totally going to steal that, right on point.

**Comment by majkinetor** [comment]
Yeah, good one, added it to [1.1.11](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#111-conform-to-guidelines).

**Comment by markrendle** [comment]
@mnuzzolilo If you're interested in Open Source Project management, maybe read some articles on it instead of trolling* actual projects. Start with this: https://rfc.zeromq.org/spec:42/C4/

(*Yes, you are. Here's a summary:

You: I have a problem.

...11 month lacuna...

Project: That's not supported.

You: [passive aggression]

Project: Maybe you could fix it?

You: No, because I am an entitled free-loader.

Project: Right, bye then.

You: Haha! Fooled you all! This is an experiment for my Sociology 101 homework!

Everyone: Oh, just _[expletive deleted]_ off.

FIN.)

**Comment by ferventcoder** [comment]
Probably time to lock this thread.

**Comment by gep13** [comment]
**NOTE:** For anyone who finds this and was wondering what all the conversation was around, it looks as though @Nuzzerino has chosen to delete all the comments that they left in this thread.

**Comment by gep13** [comment]
@ghuntley captured a screenshot of the conversation, and I have decided to paste it here for clarity on what was discussed in this issue.

**NOTE:** In the screenshot, the name of the original author was @mnuzzolilo, however, shortly after this issue was closed, this was changed to @Nuzzerino, and it is now @Mnuzz. 

![image](https://cloud.githubusercontent.com/assets/1271146/20642707/15805006-b40e-11e6-98cf-f28fab297fc4.png)
