### ISSUE TITLE
(autohotkey.portable) Package 2.0 alpha

### ISSUE THREAD

**Issue by franklinyu** [chocolatey/chocolatey-coreteampackages#1113]
https://autohotkey.com/v2/

Latest release available at https://autohotkey.com/download/2.0/AutoHotkey_2.0-a099-ca386dc.zip; `a099-ca386dc` probably means alpha release 99 at commit [`ca386dc`](https://github.com/Lexikos/AutoHotkey_L/tree/ca386dc3b520ae9d4b177c672b81755a1398f701).

**Comment by AdmiringWorm** [comment]
Personally I wouldn't mind something like this to be added, if someone would be willing to add it as a PR (can be added as a STREAM).

**Comment by majkinetor** [comment]
It should be added as steam as it is 100% certain that 1.x version will be kept with fixes for conceivable future. 

I wouldn't be so confident about AHK 2 release, it can still take years because Lexiskos is main developer and he 'does with AHK whatever he wants whenever he feels like it' :) [ not a judgement, its his own words].

I will be the first one to switch to 2.0 and release a package when it comes close to be released. Untill then I would close this ticket.

**Comment by franklinyu** [comment]
@majkinetor Why does it matter that it takes long to get out of alpha? I understand if you don’t want to invest the effort, but at least this should be “PR welcome”?
