### ISSUE TITLE
Create Shims for Calibre Package

### ISSUE THREAD

**Issue by YenForYang** [chocolatey/chocolatey-coreteampackages#1114]
I've noticed that Shims aren't being created for Calibre (probably because it adds itself to the Path variable).

Is is possible to use shims instead?

Note the addition of Calibre onto Path can be turned off simply by setting the `ADDLOCAL` Public Property to not include it:

```shell
# Default installation properties:
# DS is for Desktop Shortcut, FSMS is for Start Menu Shortcut
calibre-3.31.0.msi /quiet ADDLOCAL=MainApplication,Complete,FSMS,DS,FAddToPath

# Removal of Add To Path
calibre-3.31.0.msi /quiet ADDLOCAL=MainApplication,Complete,FSMS,DS
```

**Comment by AdmiringWorm** [comment]
IMO, I don't really see the benefit of changing it from adding to the `PATH` environment variable to creating shims instead (other than pollution of the PATH environment variable of course).

I think this falls more into user specific configurations, rather than something the package should handle (but again, that's just my opinion).

I'll leave this open for now though, to encourage discussion on the topic.

**Comment by majkinetor** [comment]
Calibre has number of internal tools. We need to spam with shims because of this, so in this case i prefer PATH.

Calibre adds itself in WinApps registry so CTRL+R calibre will run it. With my function [Set-AppKeyAliases](https://github.com/majkinetor/posh/blob/master/MM_Admin/Set-AppKeyAliases.ps1) you can have the same effect as shim today.

If something needs to be changed, that is the web server automation eventually, but that is offtopic for this case.

I will close this due to the current answers.
