### ISSUE TITLE
(totalcommander) Install only x64 version on x64 system

### ISSUE THREAD

**Issue by kintrupf** [chocolatey/chocolatey-coreteampackages#1174]
When installing Total Commander on an x64 system both the x32 and the x64 versions are installed, including desktop icons and such.

There are separate installers available for x32 and x64 systems on the Total Commander website, so it would be great if these installers are either downloaded on demand or included in the nupkg file instead of the combined version.
I think there is very seldom a need for both versions to be installed on the same system :-)

**Comment by majkinetor** [comment]
Not really a big issue, and it was done to simplify already complex installer script (tc uses custom installer).
You may also need it for some plugins eventually. 

The package also states that in notes so it is by design:
> This package contain combined Total Commander installer which contains both x32 and x64 bit versions.

Given that the size difference is tiny, just delete the shortcut you don't need.
