### ISSUE TITLE
cURL static library

### ISSUE THREAD

**Issue by cup** [chocolatey/chocolatey-coreteampackages#1241]
It appears that Chocolatey is using Viktor Szakats @vszakats version of cURL:

https://github.com/curl/curl-for-win

this is problematic for 2 reasons. First that repo offers no issues, so if a
problem arises not with cURL but with the build itself users have little
recourse.

Second, that build does have an issue. Viktor has not built cURL with
`-DNGHTTP2_STATICLIB`. Because of this, the static libcurl is built that relies
on shared nghttp2. I reported the issue upstream:

https://github.com/curl/curl/issues/2516

also its been reported at the MSYS2 project:

https://github.com/msys2/MINGW-packages/issues/3538

**Comment by cup** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/issues/1241
https://github.com/curl/curl/issues/2516
https://github.com/cygwinports/mingw64-x86_64-curl/issues/1
https://github.com/msys2/MINGW-packages/issues/3538

**Comment by vszakats** [comment]
Since the commit https://github.com/curl/curl-for-win/commit/f97095f3857d63a33192f4b2f89460e7d05339fb (2018-03-13), curl-for-win enables the `-DNGHTTP2_STATICLIB` option differently than before while also switching to using CMake to build nghttp2 (before that, it was using `win32/Makefile.gcc`, which indeed requires enabling this flag manually).

In that commit I've added a patch to nghttp2 that allows building static libs via CMake. This can be enabled by CMake option `-DENABLE_STATIC_LIB=1`. This option will in turn enable `-DENABLE_STATIC_LIB=1` option [automatically](https://github.com/nghttp2/nghttp2/blob/cfb47d30a5bb5dfcc6b0dc30698957d8605348c5/lib/CMakeLists.txt#L59-L67).

This patch was at the same time [submitted](https://github.com/nghttp2/nghttp2/pull/1146) to nghttp2, where it was subsequently [merged](https://github.com/nghttp2/nghttp2/commit/4c3a3acf9bfd63f3996133ffc8e2a22fb37d14f4) and released with nghttp2 [v1.32.0](https://github.com/nghttp2/nghttp2/releases/tag/v1.32.0).

I'm using libcurl and nghttp2 both linked statically in production, and they link and do work fine either before or after the above commit.

Let me know if this answers your issue.

**Comment by cup** [comment]
@vszakats sorry but I dont find what youve said to be the case.

Perhaps it is because you havent specified what nghttp2 you are using. Here is
my current workflow.

1. Install nghttp2 from http://repo.msys2.org/mingw/x86_64
2. Install cURL from https://curl.haxx.se/windows
3. build

~~~
$ cat test.c
#include <curl/curl.h>
int main()
{
   CURL *q = curl_easy_init();
   curl_easy_setopt(q, CURLOPT_URL, "nghttp2.org/httpbin/get");
   curl_easy_perform(q);
   return 0;
}

$ x86_64-w64-mingw32-gcc test.c -DCURL_STATICLIB -static \
> -lcurl -lwldap32 -lws2_32
lib/libcurl.a(http2.o):(.text+0xbf): undefined reference to `nghttp2_version'
~~~

**Comment by cup** [comment]
@vszakats i think i see the problem

it looks like https://github.com/curl/curl-for-win is using OpenSSL 1.1

and Cygwin is using OpenSSL 1.0

I might need to build my own OpenSSL - thanks

**Comment by cup** [comment]
@vszakats the problem was i was using OpenSSL 1.0

i see that OpenSSL 1.1 is here

https://curl.haxx.se/windows

i will try and report back

**Comment by cup** [comment]
https://github.com/cygwinports/openssl/issues/1

**Comment by cup** [comment]
https://github.com/cygwinports/mingw64-x86_64-openssl/issues/1

**Comment by cup** [comment]
@vszakats I was able to get the static cURL library working. I am using Cygwin
and some Cygwin static libraries are either missing or old, so in addition to
cURL I needed to use Brotli, nghttp2 and OpenSSL from here:

https://curl.haxx.se/windows

here is the final command I used:

~~~
x86_64-w64-mingw32-gcc test.c -DCURL_STATICLIB -static -lcurl \
-lbrotlidec-static -lnghttp2 -lssh2 -lssl -lwldap32 -Wl,--start-group \
-lbcrypt -lbrotlicommon-static -lcrypt32 -lcrypto -lws2_32 -lz
~~~

and here are my build scripts:

https://github.com/cup/glade/tree/master/curl

**Comment by vszakats** [comment]
Yes, it is expected that the (well, _all_) static lib dependencies from the download page are also required for static linking. I'm glad it worked out at the end!

**Comment by majkinetor** [comment]
Anything we need to do on package ? Better docs maybe explaining this situation @cup ?
