### ISSUE TITLE
(wget) stopped working - libwinpthread-1.dll is missing from your computer

### ISSUE THREAD

**Issue by wesinator** [chocolatey/chocolatey-coreteampackages#1260]
## Expected Behavior
wget works out of the box after install

## Current Behavior
System Error "libwinpthread-1.dll is missing from your computer"
![image](https://user-images.githubusercontent.com/5124946/55694443-3ae1ae00-5982-11e9-84b7-b5894c1e12d3.png)

## Possible Solution
bundle `libwinpthread-1.dll`

## Steps to Reproduce (for bugs)

1. `choco install wget`
2. wget

## Your Environment

* Package Version used: v1.20.3
* Operating System and version: Windows 8.1 Pro x64
* Chocolatey version: v0.10.11
* Install/uninstall gist:

**Comment by majkinetor** [comment]
This is MinGW runtime lib. Possibly you should report this to authors of the wget.

Try installing mingw and finding the lib there: https://chocolatey.org/packages/mingw

Not sure if there is anything else we can do here.

**Comment by wesinator** [comment]
reported to https://savannah.gnu.org/bugs/index.php?56105

`choco install mingw` did not fix it

**Comment by rockdaboot** [comment]
> This is MinGW runtime lib. Possibly you should report this to authors of the wget.

Wget is not multi-threaded and so we don't link with pthread or it's Windows variant. Of course I can't promise that for our dependencies. Those may or may not need pthreads. IMO, we can't do anything about it.

**Comment by rockdaboot** [comment]
libcrypto, libpcre2, libssl (OpenSSL) and libgnutls pull in libpthread. So if your build/package contains one of them, you need pthread / libwinpthread as dependency in your package.

**Comment by majkinetor** [comment]
> `choco install mingw` did not fix it

It didn't, because it can't.  You need to put the dll from there, to some of the known places on Windows - try putting it in `wget.exe` dir or copy it to system32 folder etc.

>  So if your build/package contains one of them, you need pthread / libwinpthread as dependency in your package.

We don't build the wget. We just download from official place (https://eternallybored.org/misc/wget) the highest version of the zip files and put it in the zip file (nupkg) along with some metadata. 

@wesinator will certainly have the same problem using your build without a chocolatey involved.

**Comment by majkinetor** [comment]
@wesinator you could walk the dependencies and find out which one needs the lib and report here. U could use https://chocolatey.org/packages/dependencywalker

**Comment by jernejs** [comment]
libwinpthread-1.dll was a compilation problem - I rereleased the binaries next day which don't need it any more, however I still wouldn't recommend 1.20.3, because it doesn't work properly with https sites due to a change in OpenSSL (the library won't initialise without a config file).

**Comment by wesinator** [comment]
> libwinpthread-1.dll was a compilation problem - I rereleased the binaries next day which don't need it any more, however I still wouldn't recommend 1.20.3, because it doesn't work properly with https sites due to a change in OpenSSL (the library won't initialise without a config file).

Ah, ok thanks Jernej

**Comment by jernejs** [comment]
I updated the binaries today, so https downloads work again.

**Comment by rockdaboot** [comment]
Thank you, Jernej !

**Comment by zpelgrims** [comment]
@jernejs Any idea when this fix (libwinpthread-1.dll) will be released?

**Comment by acolbeck** [comment]
@majkinetor After this issue was closed, jernejs updated the binaries to fix the underlying dependency issue. If you could refresh the chocolatey package as per your mention here https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1260#issuecomment-481308991 that fix will be surfaced.

**Comment by compuguy** [comment]
This issue has cropped up again with the latest release of wget, 1.21.1, @jernejs

**Comment by vg22** [comment]
> This issue has cropped up again with the latest release of wget, 1.21.1, @jernejs

Also affecting the older release 1.20.3

**Comment by jernejs** [comment]
If you download 64-bit 1.21.1 again, this issue has been fixed.

**Comment by vg22** [comment]
> If you download 64-bit 1.21.1 again, this issue has been fixed.

@jernejs  I am getting the same error. I uninstalled the existing wget and tried again. I have a local cached version of wget in my internal choco repo. Could that be a problem?

**Comment by cinderblock** [comment]
`choco install --force wget` says it redownloads the latest zip. Is it not using it or something?

**Comment by jernejs** [comment]
No idea – I don't have anything to do with chocolatey package. The wrong ZIP was on my [download page](https://eternallybored.org/misc/wget/) for about 13 hours before I caught the error. The correct ZIP has sha256 a56163475d344f9d78c28becf33015df468ddc6785c4b3d33c80095006cb5438.

**Comment by cinderblock** [comment]
I just interrupted the `choco install --force wget` and found the files that Chocolatey is downloading at `%TEMP%/chocolatey/NuGetScratch/<UUID>/<hash>/tools/`:

```log
Name: chocolateyinstall.ps1
Size: 514 bytes
SHA256: C2E33B78CCBD6FC30470E6B44EAEAA49A46C58FE3A38AF9B41938E79BD4ED50D

Name: wget-1.21.1-win64_x64.zip
Size: 4269897 bytes (4169 KiB)
SHA256: F0FFE6AAF61CCB4DBEF8DF7578FA061C8D6059CA72429DD25DEF6B64FE56B934

Name: wget-1.21.1-win32_x32.zip
Size: 4049248 bytes (3954 KiB)
SHA256: 11782DC3E3FE6C56C2193453063F9F637F4462072C703CE17FCFBAC86B1A7A49
```

@jernejs can you tell if those are cached versions of the wrong `zip`? I think Chocolatey's package cache may be stale.

**Comment by AdmiringWorm** [comment]
> @vg22
> Also there is a warning in the logs which might be related to it.

That warning is harmless, it happens just because chocolatey itself can't extract the icon from the executable when it creates the shim to put on `PATH`.

> @jernejs I am getting the same error. I uninstalled the existing wget and tried again. I have a local cached version of wget in my internal choco repo. Could that be a problem?

Dependening on the priority you have set on your sources, that can be the problem and it picks up the one you have cached instead of the one on chocolatey.org.
The log output should mention which version you installed though, as well as where it got it from (if you look inside the `chocolatey.log` file.

> @cinderblock 
> I just interrupted the choco install --force wget and found the files that Chocolatey seems to be downloading in %TEMP%/chocolatey/NuGetScratch/<UUID>/<hash>/tools/:

The package don't download any files during installation, both 32bit and 64bit archives are embedded inside the package and the checksums can be seen in the `VERIFICATION.txt` file (should be viewable both on chocolatey.org, and in Chocolatey's lib directory).

> @jernejs 
> The wrong ZIP was on my download page for about 13 hours before I caught the error

Looks like it is that wrong zip that got caught when our update script checked if there were any updates.
It didn't pick up the correct zip archive due to it being the same version as the one it had already picked up.
I'll force a new fix version for the package, which should be available on chocolatey.org in a few hours.
