### ISSUE TITLE
WriteErrorException,cyg-get.ps1

### ISSUE THREAD

**Issue by fatso83** [chocolatey/chocolatey-coreteampackages#176]
I really have no idea why I am having troubles with `cyg-get`. It talks about not being able to find a file, but it seems clearly to be present. 

I installed choco+cygwin+cyg-get on another machine just hours before this happened. The only difference I can think of is that Cygwin used to be manually installed before trying to install it through Choco.

This is the output straight after installing choco and opening a new admin terminal:

```
PS C:\Windows\system32> choco install cyg-get
Installing the following packages:
cyg-get
By installing you accept licenses for the packages.

Cygwin v2.4.1
The package Cygwin wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
1
 Downloading Cygwin 64 bit
   from 'https://cygwin.com/setup-x86_64.exe'
 Installing Cygwin...
 Starting cygwin install, version 2.873
 User has backup/restore rights
 Current Directory: C:\ProgramData\chocolatey
 Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.
 root: C:\cygwin64 system
 Selected local directory: C:\ProgramData\chocolatey
 net: Direct
 site: http://mirrors.kernel.org/sourceware/cygwin/
 Changing gid back to original
 running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_000_autorebase.dash"
 running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_update-info-dir.dash"
 Changing gid to Administrators
 Ending cygwin install
 Cygwin has been installed.
 The install of cygwin was successful.

cyg-get v1.2.1
The package cyg-get wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
1
 Adding C:\ProgramData\chocolatey\bin\cyg-get.bat and pointing it to powershell command C:\ProgramData\chocolatey\lib\cy
g-get\tools\cyg-get.ps1
 The install of cyg-get was successful.

Chocolatey installed 2/2 package(s). 0 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\Windows\system32> cyg-get openssh
Attempting to install cygwin packages: openssh
C:\ProgramData\chocolatey\lib\cyg-get\tools\cyg-get.ps1 : Please ensure you have Cygwin installed.
To install please call 'choco install cygwin' (optionally add -y to autoconfirm).
ERROR: This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ & 'C:\ProgramData\chocolatey\lib\cyg-get\tools\cyg-get.ps1'  openssh
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,cyg-get.ps1

PS C:\Windows\system32>
```

**Comment by fatso83** [comment]
This might be fixed by #125, if that gets fixed.

**Comment by tlin-fei** [comment]
Change the value of $cygwinsetup to the following $cygwinsetup = "$cygRoot\setup-x86_64.exe" in cyg-get.ps1 file

**Comment by fatso83** [comment]
@tlin-fei : Thanks for the input, but observe my comment above: there is already a pending PR that will fix this issue. I just applied the patch to fix my problem.

**Comment by tadeu** [comment]
I'm having this problem too, and the latest cygwin (v2.5.0) does not seem to have `setup-x86_64.exe` or `setup.exe`

**Comment by cwiggs** [comment]
@tadeu I found a workaround for this issue.

1. Download the setup installer on the cygwin website: [https://cygwin.com/setup-x86_64.exe](https://cygwin.com/setup-x86_64.exe)
2. Rename the installer to cygwinsetup.exe
3. Move the installer to C:\tools\cygwin (or wherever you install cygwin)

**Comment by rahulserver** [comment]
@cwiggs your workaround works for me too!

**Comment by datavirtue** [comment]
cwiggs work around solved my issue

![image](https://cloud.githubusercontent.com/assets/1112636/18534818/e8c2aa30-7abc-11e6-952d-eb339555c647.png)

**Comment by silentcoast** [comment]
@cwiggs thanks for posting. Just installed fresh today and still having the same issue your work around fixed it.

**Comment by dwbimstr** [comment]
I am still having issues. tried the fix suggested by @cwiggs  but did not work 

![image](https://user-images.githubusercontent.com/17050406/26983424-c2c52efa-4d09-11e7-8f33-da2ecd9353cd.png)

**Comment by ferm10n** [comment]
@dwbimstr I had the same issue.
I started by removing cyg-get and cygwin, then `choco install cyg-get -y` (note that I left out cygwin)
then I followed @cwiggs steps. I then was able to 
`cyg-get openssh`

But now I don't know how to install sshd as a service after that. Can anyone offer suggestions?

Side note, I'm really surprised this issue is still present a year later. Wouldn't this be just a simple matter of checking if 32 or 64 bit and downloading the correct installer?

**Comment by majkinetor** [comment]
This `cyg-get` script is badly written.

I suggest people remove try / except block and see why it actually fails. While the cygwin package was recently changed to ensure setup is on right location, this is probably some other type of error.

**Comment by derekmahar** [comment]
I solved this problem by completely removing `Cygwin`, deleting registry keys `HKLM:\SOFTWARE\Cygwin\setup` and `HKLM:\SOFTWARE\Wow6432Node\Cygwin\setup` (removing `Cygwin` should remove the former), and then reinstalling `Cygwin` and `cyg-get`.

In my case, the cause of the problem was that one of the registry keys `HKLM:\SOFTWARE\Cygwin\setup` and `HKLM:\SOFTWARE\Wow6432Node\Cygwin\setup` pointed to an invalid Cygwin root path and script `cyg-get.ps1` was using the one which was invalid, preventing it from finding Cygwin.  The Chocolatey Cygwin package creates registry key `HKLM:\SOFTWARE\Cygwin\setup`, but not `HKLM:\SOFTWARE\Wow6432Node\Cygwin\setup`, so an earlier installation of the regular Cygwin setup must have created this key.

**Comment by DeepenNegi** [comment]
$ cyg-get wget
Attempting to install cygwin packages: wget
C:\ProgramData\chocolatey\lib\cyg-get\tools\cyg-get.ps1 : Please ensure you have Cygwin installed.
To install please call 'choco install cygwin' (optionally add -y to autoconfirm).
ERROR: This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ & 'C:\ProgramData\chocolatey\lib\cyg-get\tools\cyg-get.ps1'  wget
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,cyg-get.ps1

**Comment by pauby** [comment]
@DeepenNegi this issue was closed 8 years ago. You're not going to get a response to your comment. 

Please raise a new issue.
