### ISSUE TITLE
(Python3-x86_32) Attempts to create ignore files for the entire computer

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#208]
https://github.com/chocolatey/chocolatey-coreteampackages/blob/220dfd6552a78894cfd01b63ae301a8a7f0773fa/automatic/python3-x86_32/tools/chocolateyInstall.ps1#L24

`$destination` is not defined. Please fix.

**Comment by dtgm** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/issues/79#issuecomment-182895775

**Comment by majkinetor** [comment]
I wont do any work on those packages since it is now artifact of the upstream choco problem (not remembering install parameters). Once that is fixed, passing `force86` on first install would be enough.

Am I right @ferventcoder  ?

**Comment by ferventcoder** [comment]
This issue here is solely in the package itself - has nothing to do with how you pass args

**Comment by majkinetor** [comment]
The question is semi-related to issue here. SInce python3 has this behvior fixed already, the same fix should be apply in this package.

However, this package exists solly because updating forced86 python will change it to x64 version as install parameters are not remembered. Once this works, this package can be deprecated.

**Comment by ferventcoder** [comment]
Oh. Got it. Sorry, thought this was about the issue at hand and not the pkg itself. Makes sense

**Comment by majkinetor** [comment]
Will be deprecated on https://github.com/chocolatey/choco/issues/797.
