### ISSUE TITLE
(PandaFreeAntivirus) Ketarin job error

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#235]
@Redsandro can you take a look at this?

When trying to run the ketarin job, I see the following in the log:

```
2016-06-13 18:32:53,866 [ERROR] - The packages folder 'C:\code\mine\chocolateyautomaticpackages\Panda Free Antivirus' does not exist. Perhaps you meant to specify the name as something else or you want to override the packages folder path setting of 'C:\code\mine\chocolateyautomaticpackages'. See chocopkgup.exe /help for details.
```

Something doesn't look right to me in the xml file, there are two Jobs nodes.  Is that intentional?

**Comment by Redsandro** [comment]
I'm not sure. I'm not seeing what you are referring to. I don't see the double job node? Could you quote line numbers?
https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/PandaFreeAntivirus/PandaFreeAntivirus.ketarin.xml

I just cut copied the xml part from my own autopackage (which never gets to run amymore because I don't have a running Windows machine since 2014 or so) and removed the ExecuteCommand part.

Could it be that the way the script in the ketarin machine works it needs to have a spaceless name? E.g. this:

```
<Name><placeholder name="Name" value="Panda Free Antivirus" /></Name>
```

Shoud be this:

```
<Name><placeholder name="Name" value="PandaFreeAntivirus" /></Name>
```

This is just my best guess based on looking at the XML, the error message and knowing something doesn't work, but it might be unrelated.
