### ISSUE TITLE
chromium issues

### ISSUE THREAD

**Issue by Link-Satonaka** [chocolatey/chocolatey-coreteampackages#238]
The "mini_installer.exe" of this package drops chromium into the Appdata of the installing user, which is not a functional location for multi user systems.

Furthermore, this is the "chromium" package, but it provides snapshot builds. This should be providing stable releases, which are available from the same source currently used.

https://github.com/chocolatey/chocolatey-coreteampackages/issues/196#issuecomment-204979417
@woolyss I can't seem to get the other installers you provide to work. They silently crash without presenting a GUI, and Windows defender detected three (!) different trojans from the chromium-sync.exe package provided on your site. We may need your cooperation in providing us with something that properly installs to Program Files.

Thanks!

**Comment by woolyss** [comment]
> The "mini_installer.exe" of this package drops chromium into the Appdata

**Lee James** done a good suggestion about that, at https://chocolatey.org/packages/chromium#comment-2613353872

$ mini_installer.exe --system-level --do-not-launch-chrome

The above commandline installs Chromium to the appropriate %ProgramFiles% directory, and also suppresses the first-run dialog, which is often beneficial.

>this is the "chromium" package, but it provides snapshot builds. This should be providing stable releases

There is NO **stable** OFFICIAL Chromium version. The official developers of Chromium project do not release a stable version of this browser to end users. They release Google Chrome as stable Chromium version. So, the official releases of Chromium are only the snapshot builds. The Chocolatey team prefers to use official Chromium builds.

> I can't seem to get the other installers you provide to work.

Most of people has not unique issue with stable installers because the stable version == google chrome version. So, there are the same bugs, issues, problems.
If you do not trust me, compile Chromium yourself and compare your own release with google Chrome.

> Windows defender detected three (!) different trojans

We know that for for few years ago: http://chromium.woolyss.com/#malware

I encourage you to compile Chromium yourself. http://chromium.woolyss.com/#source-code
You will have the same result on your antivirus ;)

But note the **VirusTotal result** of the latest version say all is clean and safe:
Installer [Sync..  51.0.2704.103 (386251) • Thursday, 16 Jun 2016]
https://www.virustotal.com/en/file/fef3404e5239254f7418fc41d0c4f5e40d00bf17dcdbf9fce343d4b3ee3fee19/analysis/

Check yourself ! ;)

**Comment by Link-Satonaka** [comment]
>There is NO stable OFFICIAL Chromium version

Oh I know, I read your site. You provide the version that becomes release version Chome, and you also note that linux has "release builds".

This package should be using these release builds. Snapshots could still be provided as a beta (which is what it is) in the proper way that chocolatey provides for betas, the  -pre swtich. `choco install chromium -pre`.

>But note the VirusTotal result of the latest version say all is clean and safe

I did check virus total, I just thought it was curious that Windows reported three separate trojans, one of them relating to adobe flash. Will Defender remove an install of chromium from Program Files?

**Comment by woolyss** [comment]
>This package should be using these release builds

Agree with your good suggestion.

>Will Defender remove an install of chromium from Program Files?
Maybe. I do not use it.
I prefer an independent antivirus. I choose Avira. There is no problem with Chromium, Flash or Google Chrome.

**Comment by ferventcoder** [comment]
Note that VirusTotal is run against all packages, including remote
resources it needs to download first. That means at the time the package is
approved, the binaries are validated to be fine. Of course the remote
resources can change later, so the checks on the site are only good when
the hashes match. For that reason we suggest Choco Pro, it does a runtime
check of what is actually downloaded against VT.

On Sunday, June 19, 2016, Jerry <notifications@github.com> wrote:

> This package should be using these release builds
>
> Agree with your good suggestion.
>
> Will Defender remove an install of chromium from Program Files?
> Maybe. I do not use it.
> I prefer an independent antivirus. I choose Avira. There is no problem
> with Chromium, Flash or Google Chrome.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/chocolatey/chocolatey-coreteampackages/issues/238#issuecomment-226984002>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAD4Duhkp95wZ0yILinroNyOONuEgyGBks5qNPE8gaJpZM4I5E30>
> .
>


-- 

Rob
"Be passionate in all you do"

http://codebetter.com/robreynolds
http://ferventcoder.com
https://twitter.com/ferventcoder

**Comment by RedBaron2** [comment]
I have proposed a new install file for chromium that will if detection the Chromium install Key into the HKCU or HKLM. The #246 Pull request is referencing the new install file.

This will require the first install to be done with the command line switches like so `mini_installer.exe --system-level --do-not-launch-chrome`

I hope this also gets the chromium package up to the latest version of 54.0.2792.0 as of 07/08/2016 at 1810PST

**Comment by woolyss** [comment]
Thank you RedBaron2 for your proposition. All seems works fine!

**Comment by RedBaron2** [comment]
@woolyss Thanks for taking the time to check, and more thanks for the website.

@ferventcoder @gep13 Could you double check on PR #246 and PR #259 adding these to the current

**Comment by gep13** [comment]
@woolyss @RedBaron2 I have just merged both of the open PR's, so lets see how this goes.

Going to close this for now, feel free to re-open if required.

**Comment by Link-Satonaka** [comment]
@woolyss One flaw until perfection! The `--system-level --do-not-launch-chrome` installs to `Program Files (x86)` even though it only contains an x86_64 binary. It should only install to `Program Files`.

Thanks

**Comment by RedBaron2** [comment]
> ...  This is known, and intentional, for the time being. 
<chromium Issue '380177' comment number 30 at bugs.chromium.org>

@Link-Satonaka This is a problem with the installer for Chromium.

Everyone else this issue has been solved. Thank You for all your help. :+1:
