### ISSUE TITLE
eclipse

### ISSUE THREAD

**Issue by 030** [chocolatey/chocolatey-coreteampackages#256]

**Comment by majkinetor** [comment]
This ticket is useless so I'll close it.

**Comment by gep13** [comment]
@majkinetor this issue is related to the PR that was created, and which is linked in this issue.  I can understand closing it once the PR is either merged or closed, but not before.

**Comment by majkinetor** [comment]
There is no value in it, PR itself is a form of an issue.

**Comment by majkinetor** [comment]
Furthermore, it will stay linked from PR, it just doesn't have to stay open and get me 10s lost each time I browse the issues since there is no action to be done here.

**Comment by gep13** [comment]
In the case of this issue, I think I would agree with you, but in general, no I don't agree.  

Creating an issue first to discuss a topic is far better than discussing in a PR.  Too many times I have been in a situation where work has been done in a PR that hasn't been able to be merged (which means wasted effort on the part of the contributor) that could have been saved by first discussing the intended approach and implementation in a related issue first.

>@majkinetor said...
it just doesn't have to stay open and get me 10s lost each time I browse the issues since there is no action to be done here.

That would be where usage of Labels would come into play, similar to what @ferventcoder does extensively on the Chocolatey Repository.

**Comment by majkinetor** [comment]
If I ever want something **generally**, I will always explicitelly say so. Otherwise, everything is contextual.
