### ISSUE TITLE
FossHub Problems

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#265]
Based on this:

http://us8.campaign-archive1.com/?u=86a6d80146a0da7f2223712e4&id=f2fe8dbe6b

Something needs to be done about the following packages:

- [x] audacity
- [x] avidemux
- [x] lightalloy
- [x] mkvtoolnix
- [x] palemoon

Either we need to:

* not use FossHub and find an alternative download location
* or add a checksum to each package which will ensure that the correct, untampered, binary is downloaded

**Comment by ferventcoder** [comment]
OR both - use an alternate download location AND use checksums. Checksum requirement for all newly approved packages is likely moving up in the schedule based on this event.

**Comment by Redsandro** [comment]
@ferventcoder can you show us an example of how to implement checksums in an autopackage? _No-one_ wants to do that stuff manually, and by no-one I mean me and probably most or all members of this repo. :smile: 

@gep13 can you explain (for all intents and purposes, not just this one) how we would get from this point to having a fixed package with no new version repushed to the gallery, in a software-less platform-independent way?

Roughly something like this I assume:

* `git clone --depth=1 git@github.com:chocolatey/chocolatey-coreteampackages.git`
* fix package code
* `git push origin master`
* :question: update ketarin machine
* :question: trigger forced update of package

**Comment by Redsandro** [comment]
@gep13 Damage has already been done. Assuming FOSSHub fixed their problems:

* `palemoon` works for now because new packages have automatically been pushed.
  * The Chocolatey virus scanner approved the package.
* The other packages can be re-pushed
* Add hash later, for now, users cannot install the packages.

**Comment by gep13** [comment]
@Redsandro yes, there is a mechanism to do this.  @dtgm is already doing it on his repo.  I have reached out to him in order to try to figure out how to do it.

**Comment by gep13** [comment]
@Redsandro not sure I follow your second question though, sorry.

**Comment by Redsandro** [comment]
@gep13 will you quote here once @dtgm responded? I assume he's using something like the code I linked in my first post.

@gep13 
> @Redsandro not sure I follow your second question though, sorry.

Well, assuming you mean my second question in my [first reply](https://github.com/chocolatey/chocolatey-coreteampackages/issues/265#issuecomment-237497703), imagine a package is fixed with a checksum generator in this repo and/or the source is now clean. Can I trigger a forced update on the ketarin machine of that package even if no _new_ version of the software is released yet? Can you do it**? Who else can do it? How does it work? If it can't be done, should some way of doing that be implemented on the ketarin machine? I assume mass-trouble will happen again, affecting too many packages at once for manual and local repushing.

As for my [second reply](https://github.com/chocolatey/chocolatey-coreteampackages/issues/265#issuecomment-237504565), third question if you will, see ** above.

**Comment by ferventcoder** [comment]
>  I assume mass-trouble will happen again, affecting too many packages at once for manual and local repushing.

We've moved up the schedule on checksum requirements, so the community will be more covered. 
https://github.com/chocolatey/choco/issues/112

For scripts - most of the work is done in https://github.com/dtgm/chocolatey-packages/blob/master/scripts/ketarin-settings-commands-02-afterupdatingapp.cs#L53 (@dtgm) and dtgm has shared how to hook that in before.

**Comment by ferventcoder** [comment]
More information on moving up the schedule - we are flipping the switch on the checksum requirement on the community feed, so all new packages will need to be checksummed if they download resources.

**Comment by Redsandro** [comment]
@ferventcoder 
> all new packages will need to be checksummed if they download resources

So basically all packages here are broken now. :smile:

We need to implement this in the ketarin global packages config @gep13 @TomOne . I didn't think it would be so complex. I was hoping ketarin had a built-in method for that.

@ferventcoder it will take some time to figure this out. And this will be problematic for all those individually maintained packages that download an installer that is always the latest version.

**Comment by ferventcoder** [comment]
> So basically all packages here are broken now. 😄

Not at all. They will just throw up big errors in the next version of choco and require a consumer to make that safety decision, not just leave it in the hands of the maintainers of the package.

We've been saying we are going to make checksums a requirement for some time now, we just no longer have the luxury of a smooth transition for the community like we'd originally hoped. 

> And this will be problematic for all those individually maintained packages that download an installer that is always the latest version.

Agreed, but we've tried to pull folks away from doing it that way for some time. 

We've always called this an anti-pattern because packages are point in time. Consider that for some things we can move to embedding that software into the packages themselves (where appropriate, distribution rights still apply).

**Comment by Redsandro** [comment]
@ferventcoder 
> We've been saying we are going to make checksums a requirement for some time now

I believe you! Where exactly? Just curious. First time I'm hearing of it. Let me explain why.

I used to get a lot of information and call to action from:

* Notifications/push mail
  * Choco github
  * Core team github
  * Choco twitter
  * Google groups
  * Chocolatey webadmin
  * Kickstarter mail
  * Maintainer discussion
* Manually check
  * Chocolatey.org
  * Puppet Blog
  * Choco wiki
  * Google groups
  * Choco gallery admin panel notes
 
It became 'a bit' too much, especially since the kickstarter took off. It was fun for a year or two, but these days I dread the hourly/daily or even weekly reminders that I sometimes dedicate a portion of my time to chocolatey. So at some point I stopped checking and I redirect _everything_ to the trash bin. My life has been an oasis of peace ever since. Sometimes a github notification slips through, or sometimes, when I dedicate the time, I actively check github and do PRs.

Ideally we'd have a single _low traffic_ source of _important_ information that doesn't blend in with the rest of the noise.

I remember suggesting a single source of information ~~about a year ago~~ [three years ago](https://github.com/chocolatey/chocolatey.org/issues/37). And/or options to tone down the volume of webadmin mail, like subscribing to specific packages (for which I can't find the specific issueon github - perhaps it was a discussion in the google groups.) There's now more of an all or nothing approach, and I won't be the only one choosing nothing over all. Just saying. But this is starting to be very off-topic.

**Comment by ferventcoder** [comment]
> Ideally we'd have a single low traffic source of important information that doesn't blend in with the rest of the noise.

We do, it's the newsletter.

**Comment by ferventcoder** [comment]
> I remember suggesting a single source of information about three years ago. And/or options to tone down the volume of webadmin mail, like subscribing to specific packages (for which I can't find the specific issue on github - perhaps it was a discussion in the google groups.) 

And we've taken significant steps to reduce that traffic. From a moderator sense, that traffic has really been reduced.

**Comment by Redsandro** [comment]
> From a moderator sense, that traffic has really been reduced.

I would like to take this opportunity to emphasize that Chocolatey has really shapen up to be a very sweet deal. There has been lots of improvements all over.

**Comment by ferventcoder** [comment]
I do agree that moving towards a better communication medium for all regarding important information with a very high signal to noise ratio. Typically that is done over the newsletter, but we need to do more in a single place to get information out. We are looking at options for this. Especially related to package maintainers on the community repository.

**Comment by ferventcoder** [comment]
When you run `choco new` for packages, the documentation generated in there has been stating as much. As you've looked over the documentation surrounding `Install-ChocolateyPackage` and other items that download remote resources - https://github.com/chocolatey/choco/wiki/HelpersInstallChocolateyPackage (the checksum related parameters) 

For literally two years (August 2014), we've been saying optional but will be required later - https://github.com/chocolatey/choco/wiki/HelpersInstallChocolateyPackage/_compare/98603f30cc8d3262112e30d73a8aa0a9a234f7de...9af0e71c3653d9c1b755a8484e23671e815ec007

![image](https://cloud.githubusercontent.com/assets/63502/17413058/57f446ae-5a45-11e6-9323-76e27e9d0bd6.png)

**Comment by Redsandro** [comment]
Which newsletter specifically? From what address? I will add an exception to my filter.

@ferventcoder 
> For literally two years (August 2014), we've been saying optional but will be required later

Okay, cool. Use of the word _'literally'_ indicates a sense of frustration. I mean no ignorance. You should know that I've _generated_ my first and last packages in 2012 using the go-to templating engine at the time, and ever since, all I do is copy-paste from existing packages to create new ones because I don't have a proper workflow in Linux. And as per guidelines, all those comments are cut out. I've never seen them. I've never used `choco new` or - if it existed - the deprecated `chocolatey` equivalent.

Just so you know. It is possible to have never seen that at all without being ignorant. :smiley: 

I do remember back in Brussels you showed me `choco` runs on Linux. Which is awesome. But I never bothered to check it out, because any autopackage workflow has a dependency on Windows in `ketarin` so I thought I might as well copy/paste forever. :yum:

**Comment by ferventcoder** [comment]
> Use of the word 'literally' indicates a sense of frustration. 

In this case it was meant because it was August 2014 and this is August 2016. So *literally* ;)

**Comment by RedBaron2** [comment]
I'm going to chime in here and state that the Chromium Package has just had the PR #267 #268  #269  done to implement checksum 'md5' because of the whole FOSSHub News. This was able to be done with the help of Woolyss wonderful API.

I would like to see about having the chromium package updated more frequently than seems to be done now. If that would take becoming the package Maintainer I guess I would be up for it.

**Comment by mew1033** [comment]
It looks like the chocolatey fosshub extension is also broken as a result of this. the genlink functionality isn't working.
For now, I know this is affecting the https://chocolatey.org/packages/IrfanView package.

**Comment by gep13** [comment]
@mew1033 I have just pushed a new version, 0.2.0, of the Fosshub Extension, which should now work.  Let me know if you are still having issues with it.

**Comment by gep13** [comment]
okay, finally in a position to close this one off! 😄
