### ISSUE TITLE
Chromium uninstallation not working

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey-coreteampackages#341]
When testing the uninstallation of the new chromium package on the test environment, I got this:

![image](https://cloud.githubusercontent.com/assets/1271146/19377974/f709b642-91e1-11e6-918a-2bca07c72f6b.png)

@RedBaron2 any chance you can have a look at this?

Is the uninstall.ps1 file required?  Does the auto uninstaller work?

**Comment by majkinetor** [comment]
FYI, the package is out on choco:

## Pushed


|Name|Updated|Pushed|RemoteVersion|NuspecVersion|
|---|---|---|---|---|
|[chromium](https://chocolatey.org/packages/chromium/56.0.2891.0)|[True](#chromium) &#x1F538;|True|56.0.2891.0|56.0.2890.0|

**Comment by gep13** [comment]
:+1: yip, that is fine.  A work uninstallation is not a "requirement" yet, so was happy to push it package out, knowing that there was a new version.

**Comment by RedBaron2** [comment]
@gep13 

> Is the uninstall.ps1 file required? Does the auto uninstaller work?

Yes the uninstall.ps1 file is required. Auto does not remove it from "Programs & Features"
I found the solution, and it was the reason why 
> 
return $file before call to Uninstall-ChocolateyPackage ?

was in the Uninstall file. It returns the proper variable `$file` to the  Uninstall-ChocolateyPackage.
Basically how it is now it gives the path like this 
`"C:\Program Files (x86)\Chromium\Application\version\Installer\setup.exe" --uninstall --systemlevel`
with `return $file` it is like this
`""C:\Program Files (x86)\Chromium\Application\version\Installer\setup.exe" --uninstall --systemlevel"`
The difference is the extra double quotes . The `return $file` is needed because with it after `$file` `Uninstall-ChocolateyPackage` finds the file. It then uninstalls properly.

**Comment by gep13** [comment]
@RedBaron2 well done for finding the solution.  Are you able to submit a PR to correct?

**Comment by RedBaron2** [comment]
working on it and the update for the AU update file soon

**Comment by RedBaron2** [comment]
PR#345 will fix the Uninstall Issue, and is future proofing the Update file for the changes that are being made to the API strings
