### ISSUE TITLE
Can someone add SideSync to the big ketarin machine?

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey-coreteampackages#38]
It's here: https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/sidesync

**Comment by Redsandro** [comment]
There is an update but I cannot update it from my machine because I haven't figured out how to update my `cpush` license on my machine.

**Comment by gep13** [comment]
Done.

**Comment by gep13** [comment]
Had to fix up the ketarin file for it to work though :-(

c:\github\chocolatey-coreteampackages\automatic\_output\SideSync\3.1.4.827

**Comment by Redsandro** [comment]
Sorry :( What was wrong with the ketarin file?
I'm reasonably sure I just exported it from ketarin within my virtual machine.

**Comment by Redsandro** [comment]
Ah https://github.com/chocolatey/chocolatey-coreteampackages/commit/588b0e2477c0328920a6e4475d53ec9cabbb9666

`packageRoot` is a variable pointing to the directory of the autopackages. I've had that in there since as far as I can remember, don't know if I did it myself or it came with a template. It points to the autopackages folder. Otherwise it doesn't work.

Also, although irrelevant, I'd consider `C:\Chocolatey\_work\` a dirty path (home brew). `%temp%\Ketarin\` seems cleaner because it's specifically made (the `%temp%` at least) for this kind of stuff and is supposed to get cleaned every once in a while.

**Comment by gep13** [comment]
@Redsandro not sure where packgeRoot would have come from.  I have set up the shared ketarin instance as described here:

https://github.com/chocolatey/chocolatey/wiki/AutomaticPackages

which doesn't mention it, hence not in there.  In addition, we have a common executeCommand for each package in the ketarin instance, so there is no need to make one for each package.

> Also, although irrelevant, I'd consider C:\Chocolatey\_work\ a dirty path (home brew). %temp%\Ketarin\ seems cleaner because it's specifically made (the %temp% at least) for this kind of stuff and is supposed to get cleaned every once in a while.

Since this is a dedicated instance, do we need to clean things up?  There is some logic to prevent the need to download the applications, if it already exists, and the version hasn't changed.  Surely removing the files would cause them to be downloaded again, when there is no need.

**Comment by Redsandro** [comment]
> Surely removing the files would cause them to be downloaded again, when there is no need.


If that is the case, I am misunderstanding how ketarin works. I was under the impression it would only download the binary when checking for updates if there is an actual update (AKA the version number changes).

**Comment by gep13** [comment]
> would only download the binary when checking for updates if there is an actual update

I will be honest and say that I honestly don't know.
