### ISSUE TITLE
(fosshub.extension) Download URL within "xdts"-attribute

### ISSUE THREAD

**Issue by iTob191** [chocolatey/chocolatey-coreteampackages#414]
The package does no longer work for me because the download url of the binaries is stored within the xdts-attribute of the link now instead of the data-attribute.

https://github.com/chocolatey/chocolatey-coreteampackages/blob/e17820954cdce01bf1979a4ecaa7b7baa0612706/extensions/chocolatey-fosshub.extension/extensions/Get-UrlFromFosshub.psm1#L33

**Comment by bcurran3** [comment]
This is what happens when I try to use it in the Irfanpackage:

C:\ChocolateyPackages\__PUBLISHED__\irfanview>cinst irfanview.4.42.0.20161128.nupkg -force
Chocolatey v0.10.3 Professional
Installing the following packages:
irfanview.4.42.0.20161128.nupkg
By installing you accept licenses for the packages.

irfanview v4.42.0.20161101 (forced)
irfanview package files install completed. Performing other installation steps.
'kzvfk3wd.pwm' is of content type 'text/html; charset=utf-8'
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Could not find a part of the path 'C:\Users\bcurran\AppData\Local\Temp\chocolatey\irfanview\4.42.0.20161101\kzvfk3wd.pwm.istext'.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Could not find a part of the path 'C:\Users\bcurran\AppData\Local\Temp\chocolatey\irfanview\4.42.0.20161101\kzvfk3wd.pwm.istext'.
Maximum tries of 3 reached. Throwing error.

Download of 'kzvfk3wd.pwm' (-1 B) completed.
'bvvv2fks.ico' is of content type 'text/html; charset=utf-8'

Download of 'bvvv2fks.ico' (-1 B) completed.
Attempt to use original download file name failed for 'IrfanView.html'.
Copying irfanview
  from 'IrfanView.html'
Cannot find path 'C:\ChocolateyPackages\__PUBLISHED__\irfanview\IrfanView.html' because it does not exist.
ERROR: Chocolatey expected a file to be downloaded to 'C:\Users\bcurran\AppData\Local\Temp\chocolatey\irfanview\4.42.0.20161101\irfanviewInstall.exe' but nothing exists at that location.
The install of irfanview was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\irfanview\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - irfanview (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\irfanview\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by iTob191** [comment]
Wtf.. Now its fdlw...
`<a href="/Audacity.html/audacity-win-2.1.2.exe" rel="nofollow" class="dwl-link xlink" file="audacity-win-2.1.2.exe" fdlw="https://download.fosshub.com/Protected/expiretime=1480533117;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9BdWRhY2l0eS5odG1s/1d642c9f1c15566c51605ac5cafb9e29cd865af8f023ca48a2c74008710ba9e8/Audacity/audacity-win-2.1.2.exe">`

**Comment by majkinetor** [comment]
There is no such thing.

Script simply needs to be more intelligent. Take all the attributes of the link and find the one that contains full URL. You are being too precise and thats the problem.

**Comment by welwood08** [comment]
I guess this is why a few of my installed packages aren't updating right now. :)

If I may make @majkinetor's suggestion more concrete:
```
- $regexPattern = "<a href=`"$hrefText`".*(?:data|xdts)=`"(.*)`""
+ $regexPattern = "<a href=`"$hrefText`".*=`"(https://download.fosshub.com/[^`"]+)`""
```

The existing regex looks like it would be too greedy if fosshub changed the order of attributes so the url wasn't last or if more quotes appeared later on the same line, hence changing the captured `.*` to explicitly exclude quote characters. Things will get more fun if fosshub decides to obfuscate the download url and use javascript to deobfuscate it.

**Comment by AdmiringWorm** [comment]
I'm reopening this, as @majkinetor said the script needs to be more intelligent.

@welwood08 That's definitely an option to parse the download url, mind opening a PR for it?

**Comment by bcurran3** [comment]
Unfortunately 0.6.0 isn't working for me either. Am I doing anything wrong?

C:\WINDOWS\system32>choco install irfanview -version 4.42.0.20161201
Parsing -version resulted in error (converted to warning):
 Cannot bundle unregistered option '-e'.
Chocolatey v0.10.3 Professional
Installing the following packages:
irfanview
By installing you accept licenses for the packages.

IrfanView v4.42.0.20161201 - Possibly broken
irfanview package files install completed. Performing other installation steps.
'dhoiniqh.1s0' is of content type 'text/html; charset=utf-8'
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Could not find a part of the path 'C:\Users\bcurran\AppData\Local\Temp\chocolatey\IrfanView\4.42.0.20161201\dhoiniqh.1s0.istext'.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Could not find a part of the path 'C:\Users\bcurran\AppData\Local\Temp\chocolatey\IrfanView\4.42.0.20161201\dhoiniqh.1s0.istext'.
Maximum tries of 3 reached. Throwing error.

Download of 'dhoiniqh.1s0' (-1 B) completed.
'ne5znfyd.2vd' is of content type 'text/html; charset=utf-8'

Download of 'ne5znfyd.2vd' (-1 B) completed.
Attempt to get headers for https://download.fosshub.com/Protected/expiretime=1480626267;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9JcmZhblZpZXcuaHRtbA==/98c3cd7cd42077cdf61aded602f315d84cffa2bd5b14485b0672ebd736edcee0/IrfanView/iview442_x64_setup.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.fosshub.com/Protected/expiretime=1480626267;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9JcmZhblZpZXcuaHRtbA==/98c3cd7cd42077cdf61aded602f315d84cffa2bd5b14485b0672ebd736edcee0/IrfanView/iview442_x64_setup.exe'.
  The remote server returned an error: (403) Forbidden.
Downloading irfanview 64 bit
  from 'https://download.fosshub.com/Protected/expiretime=1480626267;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9JcmZhblZpZXcuaHRtbA==/98c3cd7cd42077cdf61aded602f315d84cffa2bd5b14485b0672ebd736edcee0/IrfanView/iview442_x64_setup.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.fosshub.com/Protected/expiretime=1480626267;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9JcmZhblZpZXcuaHRtbA==/98c3cd7cd42077cdf61aded602f315d84cffa2bd5b14485b0672ebd736edcee0/IrfanView/iview442_x64_setup.exe'.
  The remote server returned an error: (403) Forbidden.
The install of irfanview was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\IrfanView\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - irfanview (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\IrfanView\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by welwood08** [comment]
I noticed this earlier and assumed it was a fosshub problem since my feeble attempt to download via browser also failed. My currently proposed solution won't automatically fix the irfanview package or any other consumer outside this repository since it seems fosshub has started requiring referrer on the actual download urls.

**Comment by bcurran3** [comment]
There must be a way to put a referrer into the helper. I know I've seen it somewhere in one before.

**Comment by AdmiringWorm** [comment]
@bcurran3 there is, I've already tried that with the qbittorrent package, doesn't work.
Fosshub just keep redirecting, which clears the referrer header

**Comment by AdmiringWorm** [comment]
also noticed that the expiretime they set in the url, expires approximally 4-5 seconds after html page have been requested.

**Comment by bcurran3** [comment]
Those bastards! :)
Any chance you might want to put your efforts towards a helper for FileHippo, MajorGeeks, and/or others?

**Comment by AdmiringWorm** [comment]
it certainly seems like that would be a better use of our time, instead of trying to fix fosshub.

**Comment by bcurran3** [comment]
![wersm-geek-celebration-thumbs-up-657x360](https://cloud.githubusercontent.com/assets/14026600/20815529/143436ae-b7d3-11e6-908c-046fb516aa64.png)

**Comment by bcurran3** [comment]
I've fixed the IrfanView package by just including the binaries now. No more problems for awhile. :)

**Comment by AdmiringWorm** [comment]
@bcurran3 unfortunately that will be in violation with their license:
```
3) You may not distribute, rent, sub-license or otherwise make available to others the Software
or documentation or copies thereof, except as expressly permitted in this License without prior
written consent from IrfanView (Irfan Skiljan). In the case of an authorized transfer, the
transferee must agree to be bound by the terms and conditions of this License Agreement. 
```

**Comment by bcurran3** [comment]
He actually has conflicting license statements. I do plan to e-mail him and clear it up.

From included LICENSE.txt:

IrfanView's webpage at http://www.irfanview.com/ defines the license as "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

From: http://creativecommons.org/licenses/by-sa/4.0/

LICENSE

You are free to:

Share — copy and redistribute the material in any medium or format
Adapt — remix, transform, and build upon the material
for any purpose, even commercially.
The licensor cannot revoke these freedoms as long as you follow the license terms.

That's for IrfanView.

Unfortunately there is no express statement that plug-ins are under the CC license.

**Comment by bcurran3** [comment]
^^^^^^ errr, explicit.

**Comment by simonai1254** [comment]
FYI: I could no longer find the reference to the CC license, only the [EULA](https://www.irfanview.com/eula.htm)
