### ISSUE TITLE
OpenSSL.Light has to 2 major revisions but only one Repository

### ISSUE THREAD

**Issue by Techcadia** [chocolatey/chocolatey-coreteampackages#455]
I am trying to install the newest version of OpenSSL.Light 1.0.2j. In the last 3 versions OpenSSL.Light was moved from 1.0.X to 1.1.X release branch which would normally be fine but the refactor of the SSL version actually changed which binary files where included on install. My Program requires the older 1.0.x dlls. Is there any intention to keep the LTS packages that are being maintained until 2019 around. Even if that means a separate entry for openssl.light1.0.x

Package Url: https://chocolatey.org/packages/OpenSSL.Light

**Comment by majkinetor** [comment]
That doesn't require separate entery, but since download links no longer work it would require to push embeded fix versions that will be contained within the package ( see [wiki](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#114-no-binary-files-in-repository) ).

I can't promise that anybody will tackle this given that several important issues are still open, but we are usually very fast in merging PRs.
