### ISSUE TITLE
Requiring approvals on PRs 

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#580]
IMHO it would be a good idea to add branch protection for the `master` branch, requiring changes going through pull requests and requiring approval, or at least requiring approval on pull request (since commits on master to add AU or PUSH commands can be quite hepful). 

@chocolatey/chocolateycommunitypackages Opinions about this?

**Comment by AdmiringWorm** [comment]
I agree it would make sense to require at least one approval on pull requests, but I don't think it would make sense in a few scenarios to not allow it on the master branch since this would disallow all of the following to be pushed directly: quick bugfixes, minor metadata updates, using `AU` and `PUSH` commands and updating the files during appveyor build run.

I since there there isn't anyway to require at least one approval on PR without denying directly pushing against the master branch (as far as I know), I'm kinda against it.

**Comment by pascalberger** [comment]
Ah right, there's only the option for admins to bypass approval but not to bypass the branch protection.

**Comment by AdmiringWorm** [comment]
I do think you can add individual members/teams that can bypass it as well.
But again, not entirely sure about that.

**Comment by Redsandro** [comment]
I think at least sec branch protection on master is a good idea (no force push, no delete).

As for the merge, I'm sorry. I'm not normally a clown merging random things. In the beginning there was barely any staff here and I had a lot of packages to push or fix. Tried to do as much as possible without taking up other people's time.

[![Emergency Powers](https://img.youtube.com/vi/P3jSsg1TlP4/0.jpg)](https://www.youtube.com/watch?v=P3jSsg1TlP4)
(Click to play)

But things have changed since then. Lesson learned! :+1:

**Comment by pascalberger** [comment]
@Redsandro There's actually a use case here where directly commiting to `master` makes sense, where you can use `AU` or `PUSH` keyword in commit message to force actions (See eg. [here](https://github.com/chocolatey/chocolatey-coreteampackages/commit/84b93e6a3b215491d39f94e2333620cef1f312c7)), which would no longer work if `master` requires a PR. Also the AppVeyor build commits changes back directly to `master` after a package was updated. So I think best solutions would be to give a limited user-set the possibility to directly commit to `master` (idealy just the AppVeyor build service user) and requiring PRs with approvals for everybody else.

**Comment by majkinetor** [comment]
Will only slow down things without any other benefit. Strongly against it.
Programmers should fix problems, not introduce new ones without any justification or simply due to theoretical ideas.

The core team is already selected among worthy contributes which proved their competence. Even few occasional errors in this regard do not justify this action IMO.

**Comment by majkinetor** [comment]
And it will strongly demote AU command usage `[PUSH]` and `[AU]` making them basically unusable.

**Comment by ferventcoder** [comment]
I will withhold my opinion until I understand how it plays for forward movement. I think @majkinetor  presents a strong case against it and @AdmiringWorm presents a good case for it on just Pull Requests.

Can it be locked down to just PRs? I think last time I visited branch protection there was some good stuff but it was too limiting to move forward with. So I'm curious what has changed since.

**Comment by AdmiringWorm** [comment]
@Redsandro said:
> I think at least sec branch protection on master is a good idea (no force push, no delete).

I believe the master branch is already a protected branch which disables force push and deletion.

@ferventcoder said:
> Can it be locked down to just PRs?

Not as far as I know, the information where you enable **Require pull request reviews before merging** also states as such:
> When enabled, all commits must be made to a non-protected branch and submitted via a pull request with at least one approved review and no changes requested before it can be merged into master.

**Comment by gep13** [comment]
@ferventcoder these are the options:

![image](https://cloud.githubusercontent.com/assets/1271146/22889285/7942d520-f200-11e6-9ae3-0f03b500c688.png)

**Comment by ferventcoder** [comment]
So no. I'm pretty against this if it is not able to be locked down to just PRs.

**Comment by pascalberger** [comment]
I'm closing this issue since it unfortunately is not possible to just require approvers and still allow certain commits on master.

**Comment by jberezanski** [comment]
A bit late to the party, but I'll just say I agree with the decision. I'm normally a fan of requiring PRs for master (we have it enabled in most repos at work), but here the disadvantages, namely 1) preventing AU command usage and 2) making quick fixes impossible, IMO outweigh the advantages. As long as force push is disabled the branch is protected enough.
