### ISSUE TITLE
Streamlining PR review process

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey-coreteampackages#586]
There is overhead on the PR review process. As some of you might remember, I hate overhead.

1. Reviewer notices 8 problems.
    * 7 times trivial _"do this"_ or _"add that"_
    * 1 issue that requires thinking on committer's end
1. Reviewer types out 7 required changes and comments about 1 issue
1. Committer amends PR with commit with 7 copy-paste changes, and works on the issue.
1. Reviewer verifies that said 7 trivialities are fixed, and checks the issue.

Can we require the reviewer to __commit__ the trivialities to the PR?

1. Reviewer commits 7 trivialities and comments about 1 issue.
1. Committer commits issue fixed.
1. Reviewer verifies that issue is fixed.

**Comment by pascalberger** [comment]
I have to disagree here. This repository has a set of [guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines) defined, which are debatable as every guidelines and some parts depend on personal preferences, but IMHO the important part is to stick to the defined guidelines and processes once defined, otherwise they just don't serve any purpose. 

As the guidelines currently are, the the expectations for packages in this repository are to be in quite some points of a higher quality as required by Chocolatey to be added to the community feed. It's of course completely up to the creator of a package if he intends to aim for this level of quality or not and it's perfectly fine if he goes the route of maintaining the package himself in another repository. But if he chooses that he wants a package maintained in this repository, an integral part of the process should be to stick to the guidelines defined by this repository. In this case IMHO it should be the task of the committer to bring the package to the required quality level expected in this repository (which is also how every open-source project I worked with does it).

If we move away from this principle I fear that this repository just ends with random people just creating PRs with quick and dirty code written and let the team members clean it up, bring it up to the expected quality, which just wouldn't work IMHO with the resources availble here especially considering that existing packages also need to be maintained.

**Comment by Redsandro** [comment]
So having to jump through hoops is the punishment for not doing it correctly in the first place?

I understand your concerns. I do think a distinction between _"random people"_ (outsiders/non-members) and known members could be made, to judge whether or not something is _"quick and dirty code"_ or honest mistakes.

__1.__ I think reviewers should be at least __encouraged__ (to use their own judgment in deciding whether) to commit when the PR is _not_ from _"random people"_ in order to streamline things, especially because of the limited resources here. Doing the hoops wastes a bit of both the committer and the reviewers' time.

__2.__ Fixes required by reviewer are not always guidelines. I think if reviewer decides not to commit, we should **require** reviewers to specify the number of the guideline (and **encourage** to **link** to the guideline(s)) to make the distinction between opinion and guideline. 

__E.g.:__ [1.1.5](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#115-provide-icon) Provide icon.

__Or:__ Please update your PR to conform to the guidelines as specified in  [1.1.5](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#115-provide-icon),  [1.2.2](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#122-obligatory-tags) and  [1.2.3](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#123-informative-description)

**Comment by pascalberger** [comment]
I don't think making a distinction between team members and non-members regarding guidelines makes sense, as both should stick to the guidelines and be reviewed equally. But I'm completely OK to differentiate between *must* requirements (as defined by the guidelines and bugs/functional impacts) and *nice-to-have* ones which don't necessarily should hold up a PR.

Unfortunately GitHub only knows two states for a review, either it is accepted or changes requested, something like "accepted with suggestions" would be nice for telling that it fits to functional expectations and the minimal requirements as defined by the guidelines, but there are some improvements which could be made based on the decission of the committer. IMHO in this case the reviewer can approve the PR with the comments containing the suggestions.

**Comment by Redsandro** [comment]
> both should stick to the guidelines

I agree. I think you have misunderstood me:

> a distinction between team members and non-members regarding ~~guidelines~~ _the recommendation to commit rather than comment_

**Comment by majkinetor** [comment]
I disagree.

The point of this kind of review is not to be a dick about it or to hinder the process but to facilitate a learning process. Reviewer can trivially easy fix the problems, but then it will have to constantly do so in the future as it will promote bad behavior. Once the author learns, the PR are usually resolved very fast. If it troubles someone to the extent that he abandons it, it tells about the level of commitment the one is ready to take to be a part of community.

I am all about efficiency but this is simply not in that domain. It will hinder process a little bit for new package maintainers but will speed the process overall as more people will write code by the guidelines and nobody will need to correct for them.

Many, many more things can get automated either as AU plugins or otherwise, and its way better route to faster PR merges. For example @AdmiringWorm implemented icon fixing thing recently. There could be plugins that check _and fix_ for number of guidelines ( https://github.com/majkinetor/au/issues/55 ). I wont do it tho, did quite a lot of work with AU for less then nothing in return, but I can provide mentoring.

**Comment by majkinetor** [comment]
>  I think if reviewer decides not to commit, we should require reviewers to specify the number of the guideline (and encourage to link to the guideline(s)) to make the distinction between opinion and guideline.

Its mostly me who made the guidelines the way there are now and the numbering thing was exactly for that reason. When I was doing reviews, I was usually specifying problems by the numbers.

**Comment by Redsandro** [comment]
> Its mostly me who made the guidelines the way there are now and the numbering thing was exactly for that reason.

Ok good.

I see consensus is against collaborative PRs in favor of a learning process. I shall close this issue.
