### ISSUE TITLE
Is it worrysome to have choco and github API keys visible for the world to see?

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey-coreteampackages#590]
The appveyor configuration shows it all. And this repository is public. Is there a way we can keep these out of the repo?

**Comment by gep13** [comment]
The values in the yml file are encrypted.

**Comment by AdmiringWorm** [comment]
you're thinking of the environment variables right?
what you see in the config file isn't the actual API keys, they are the encrypted version of those keys (can only be decrypted with the correct key, which is only available on the appveyor ci)

**Comment by Redsandro** [comment]
So clever. Didn't know that was possible. Sorry for raising the alarm. Better safe than sorry, no? :smiley:

**Comment by AdmiringWorm** [comment]
@Redsandro , @gep13 
there is also the option to set the environment variables settings/environment section on appveyor web page (instead of having them in the yml file), like I have on my own repo.

![image](https://cloud.githubusercontent.com/assets/1474648/23031136/37727ebc-f470-11e6-97e1-0c6560e6bc36.png)

**Comment by Redsandro** [comment]
@AdmiringWorm 

> there is also the option to set the environment variables settings/environment section on appveyor web page

Exactly, I was thinking of that. Configurations are mutually exclusive, except for env vars.

But then I didn't know keys in the config were encrypted. So the problem was already solved before I caught up. :)
