### ISSUE TITLE
(totalcommander) Create batch file to open TC in current folder

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-coreteampackages#601]
From the shell, when you call total commander it opens saved folders. 
It would be good to create batch file that opens it with current folder, as is the case with Explorer (`start .`).

There could also be an package option to register TC as file manager for folders so `start .` opens TC instead  explorer.

**Comment by jberezanski** [comment]
Cool ideas, but I think such features should be implemented in separate packages ("totalcommander-openhere", for example), because they are neither options of the native installer nor modifications of the installation process.

**Comment by majkinetor** [comment]
I totally don't like the idea of separate packages for this kind of thing (amounts to 2 lines of source code in existing package installer). Its a smell IMO and will quickly lead to hard to maintain and tightly coupled packages. Option will not be enabled by default and is entirely expected for this kind of tool. I will rather have entirely new TC package that I will maintain on my own repository rather then producing jungle here.

Option will make sense tho, once those are remembered on updates which will come in next release of choco AFAIK.

On semi related note, I am not sure why many guys here tend to over-complicate stuff.

**Comment by majkinetor** [comment]
When we are at that, totalcommander-openhere shell extension might also get its own option. I wasn't thinking about that tho originally, as I don't use GUI.

**Comment by jberezanski** [comment]
https://chocolatey.org/docs/create-packages#rules-to-be-observed-before-publishing-packages, rule 9: "(...) Try to split up packages as much as possible. If for example a program comes with additional modules/installers that are optional, make different packages for them instead of including all the things into one package. This idea is already widely applied for Linux packages, because it leads to a more lightweight system and reduces potential issues and conflicts."

As a user, I find it more convenient to install an additional package, extending the functionality of a program, than to try to figure out which package parameters to use (and whether the options will be retained upon upgrade). Making a separate package also makes it easier and cleaner to add the feature to an existing installation (using package parameters, I would be required to reinstall the package with --force).

> Its a smell IMO and will quickly lead to hard to maintain and tightly coupled packages.

I believe the exact opposite, that is, smaller (in terms of lines of code), more granular packages are easier to comprehend, test and maintain.

**Comment by majkinetor** [comment]
I doubt your interpretation of rule 9 very much. This thing is neither "additional module or installer". Its simply a minor tweak that doesn't deserve over-complicating stuff, in this case quite a lot versus any supposed benefit.

> As a user, I find it more convenient to install an additional package, extending the functionality of a program, than to try to figure out which package parameters to use (and whether the options will be retained upon upgrade).

As a user, I find it very troublesome. If I `choco info totalcommander` I will get a list of package params ASAP. I will not get a list of related packages, on the other hand, unless I edit the description of main package each time I add a tweak to it which, while possible, is way sub-optimal as each time we add a simple option we will have to update multiple packages. 

 > Making a separate package also makes it easier and cleaner to add the feature to an existing installation (using package parameters, I would be required to reinstall the package with --force).

So `cinst -f totalcommander /param 'xyz'` is clearly more subotpimal then `cinst totalcommander-xyz` ?! :face_with_thermometer: 

>  (and whether the options will be retained upon upgrade)

That point is invalid. Starting from the next choco version, options WILL BE retained upon upgrade, there is no IF.
