### ISSUE TITLE
(notepadplusplus.install) should mention the -x86 flag in the documentation

### ISSUE THREAD

**Issue by aseques** [chocolatey/chocolatey-coreteampackages#615]
Notepad plus comes in both 32 or 64 bit versions, but only the 32 bit version has the plugin manager (one of the most used features of the editor), moreover most of the plugins are still 32bit only.
There's already a flag to choose the 32 bit version on install, but it's only mentioned in the comments, It'd be nice to have it in the package information (as it's done with the git package i.e.)

**Comment by pascalberger** [comment]
The `-x86` flag is not specific to the Notepad++ package but a flag provided by Chocolatey. See [here](https://github.com/chocolatey/choco/wiki/CommandsInstall#options-and-switches) for a list of all available command switches.

But I see the point since it has an impact on the available features of the software and IMHO it would be good to mention the restrictions and options while installing on x64 in a notes section in the package description.
