### ISSUE TITLE
(git.install) Creates spurious Shims?

### ISSUE THREAD

**Issue by TobiX** [chocolatey/chocolatey-coreteampackages#725]
I have a shim for `Git-2.13.0-32-bit.exe` in `c:\ProgramData\Chocolatey\bin\` - While not really harmful, probably not intended ;)

**Comment by AdmiringWorm** [comment]
Yeah, that is not intended. However the installers should have been removed after the install was completed, did you by any chance install the package without running the install script?
In that case shims would be created because the installers aren't removed after install.

**Comment by majkinetor** [comment]
In a fashion `Remove-Item -Force $filePath32, $filePath64 -ea 0` which means that for some reason they might not get removed and there will be no error message (which IS good, better to have spurious shim then fail the install). Perhaps we could change that into `Remove-Item -Force $filePath32, $filePath64 -ea Continue` so that error shows but package doesn't fail ? It wouldn't really solve the problem.

I guess we can't add rm's that delete any eventual shims in case they are created as that happens after the script. We could use some mumbo jumbo tricks like removing them in Task Scheduler after several seconds but...

**Comment by majkinetor** [comment]
Or perhaps replace this line with something like this which would solve it.

`$filePath32, $filepath64 | { rm $_ -ea 0; if (Test-Path $_) { touch "$_.ignore" }`
