### ISSUE TITLE
(libreoffice-help) keeps getting rejected

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#762]
Anyone want to take a closer look at this package? Is everyone on [the mailing list](https://groups.google.com/forum/#!forum/chocolatey-coreteampackages) to receive emails when these fail (@AdmiringWorm @majkinetor)? Or are the filters turned up so much these messages are missed?

![image](https://user-images.githubusercontent.com/63502/27238322-0b02831a-5292-11e7-9b1d-0094f22a0314.png)

I took a closer look - it's failing on this: `$installArguments`. Please use a different name. See https://github.com/chocolatey/package-validator/wiki/ScriptContainsUsageOfInstallationArguments for details. If something is wrong, we may need to make a change on the validator's detection.

**Comment by AdmiringWorm** [comment]
I've honestly have yet to have a look at the libreoffice-help package (it have not yet been migrated to AU and is still using ketarin).

I do get the messages from the mailing list, but have pretty much ignored them for this package (because it haven't yet been migrated).
I doubt there is anything wrong with the validator's detection though.

**Comment by AdmiringWorm** [comment]
I've removed the ketarin file for libreoffice-help for now, since there is no reason to push a package we now will fail and eventually rejected, it definitely shouldn't be ran with ketarin.

Anyways, we still need to look into migrating the package to AU though.

**Comment by majkinetor** [comment]
Closing due to lack of interest. Moved it to manual packages as it has no AU script.
