### ISSUE TITLE
(apache-httpd) package keep installing the x86 version on x64 machine

### ISSUE THREAD

**Issue by anhddo** [chocolatey/chocolatey-coreteampackages#766]
Hi, I have a problem with the apache-httpd package. The installer kept installing the x86 version on x64 computer.
 
I notice line 53 in tools/helpers.ps1

`Get-ChocolateyUnzip 
 -file $arguments.file 
 -destination $arguments.destination`

It should check bit version on user's machine then decide $arguments.file or $arguments.file64.

**Comment by AdmiringWorm** [comment]
Thanks for opening this issue, that is indeed a problem.
Seems like the `file64` parameter have been completely forgotten (as well as a dependency on chocolatey.org).

I've added it as `Up for Grabs` if you would be interested in providing a fix for this (the only thing needed is add `-file64 $arguments.file64` to the helpers.ps1 file (on the line you mentioned), and a dependency on chocolatey version 0.10.4 or greater, personally I prefer to add the dependency on 0.10.5 because the previous version was broken).

I'll update it myself in a few days though, if no one else have opened a PR for it.

**Comment by photodude** [comment]
Looks like a PR has been opened #768

**Comment by AdmiringWorm** [comment]
@photodude thanks, never noticed the PR

**Comment by photodude** [comment]
You are welcome. Just randomly noticed it myself.
