### ISSUE TITLE
(NodeJS) No package available for 4.8.4

### ISSUE THREAD

**Issue by matt-richardson** [chocolatey/chocolatey-coreteampackages#812]
NodeJS "recently" released [a security fix](https://twitter.com/nodejs/status/884822255032823810), and recommended all users upgrade to the following versions:

```
- 8.1.4
- 7.10.1
- 6.11.1
- 4.8.4
```

We are stuck on the 4.x release, but the latest package available is `4.6.1`.

Is it possible to get a new package release for `4.8.4`? (I suspect it will be useful to have `6.11.1` and `7.10.1` available as well, but we dont explicitly need it.)

I looked to see if I could submit a PR, but it appears relatively automated. If I've missed something, let me know what I need to do and I'll submit one.

Thanks!

**Comment by majkinetor** [comment]
Its automated for the latest release, not for streams. Streams complicate maintenance quite a lot IMO.

@AdmiringWorm, @pascalberger , @ferventcoder 

Perhaps we could make a method so that users can PR something like this ? For example. We could make it work via commit message:

```
(node.js) [AUStream nodejs:6.11.1]

URL32 = 'https://node....'
URL34 = 'https://node....'
ReleaseNotes =  'bla'
```
In this case AU would not call the `au_-GetLatest` but would take it from environment or something and imply force.

It should go trough testing and everything. Not sure ATM how big this job is but we get requests like this relatively frequent.

**Comment by pascalberger** [comment]
@majkinetor Sounds good to me if this would be supported by AU through commit messages

**Comment by AdmiringWorm** [comment]
I believe this is now more or less easily done with the current AU streams that we are testing out.
As such I plan to look  into this one over the next few days.

**Comment by AdmiringWorm** [comment]
The appveyor update run is now in process of updating and pushing LTS releases to chocolatey, only what is still officially supported will be pushed.
