### ISSUE TITLE
(nuget.commandline) Update failing

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-coreteampackages#820]
## Current Behavior
Update of nuget.commandline throws an error: https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e#nugetcommandline

**Comment by majkinetor** [comment]
I wrote the AU updater for that package.

It looks like site was changed in the meantime so the scraper should be changed to reflect that. It should be trivial, but keep in mind that this is intended as reference point for other Nuget packages so that it should be general enough (here only package name needed to be changed).

Xplat package on my machine returns this when executed:

> .\NuGet.CommandLine.XPlat.exe

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Common, Version=4.3.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
```
It has bunch of dependencies while CommandLine has none. Its funny that it does so, as I have VS2017 installed.

The current AU updater doesn't handle dependencies.

**Comment by pascalberger** [comment]
> It looks like site was changed in the meantime so the scraper should be changed to reflect that. 

@majkinetor Why do you still want to scrape the nuget.org website? Since the AU script uses the NuGet package it should also check the latest available version of the NuGet package instead to determine if it should update instead of checking a website which might be out-of-date (eg. the latest mentioned version on nuget.org is 4.3 for which no `nuget.commandline` package exists but only a `nuget.commandline.xplat`)

**Comment by majkinetor** [comment]
I don't want to. It should definitely be changed to use something else

For example nuget itself could be used if nothing more appropriate exists (such as REST API) -  `nuget list id:<package_name>` in which case AU should have nuget.commandline preinstalled :+1: 

```
PS> nuget list id:nuget.commandline -Prerelease
NuGet.CommandLine 4.3.0-preview3-4168
NuGet.CommandLine.XPlat 4.3.0
```

**Comment by majkinetor** [comment]
JSON is way better, I didn't see you already used it.
