### ISSUE TITLE
(fiddler4) Please remove Fiddler to respect Telerik IP

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-coreteampackages#923]
Telerik reached out and is asking that the Fiddler package be removed as it is giving direct access to a download location they no longer show on the site. Since they have an information gateway to receive information prior to download, they have asked that we remove the package so that folks obtain the downloads directly from them.

This is not up for discussion, please keep comments respectful.

**Comment by gep13** [comment]
@ferventcoder I have removed the fiddler4 package from the AU processing, so new versions shouldn't be pushed to chocolatey.org 😢

**Comment by majkinetor** [comment]
We could still produce the package on this repository internally and make it available in releases, without making any problem with Telerik request, as it will never get pushed to gallery.

What do you think ?

**Comment by majkinetor** [comment]
It could even be considered to get embedded so that their endpoint doesn't get involved.

**Comment by gep13** [comment]
@majkinetor given the request that was received, I think it would be best to leave this package as is (i.e. preserved in the unlisted folder), and do nothing else with it.

**Comment by majkinetor** [comment]
@gep13 Sure.

I was just thinking generally about this problem. Maybe we could make a document about what users who want to depend on unlisted packages do. 

I don't use fiddler so I couldn't care less, but, I could, for example, move a package to my AU repository which isn't associated to Chocolatey as a company, and make embedded package there. This can't be distinguished from users who cached the package in the Nexus/Artifactory as unlisting doesn't affect them, its way better since only AU uses the link once.

**Comment by ferventcoder** [comment]
Please remove references to the url - that includes from this repository.

**Comment by ferventcoder** [comment]
@majkinetor thanks.

**Comment by gep13** [comment]
@majkinetor :+1:

**Comment by russcam** [comment]
Do you have any recommendations for another proxy that can be configured for automated integration tests?

**Comment by gep13** [comment]
@russcam sorry, not sure i follow your question? Can you elaborate?

**Comment by russcam** [comment]
Sure. I was using this package for integration tests, to verify that a Windows Installer is using the proxy specified by input parameters to the installer. With Fiddler, I could set up a custom rule to capture the request traffic and assert that it contains a request known to come from the installer.

I could check the fiddler executable into source (license permitting) but would prefer to install and configure one through chocolatey because it's part of a vagrant provisioning step. So I'm wondering if there is another proxy chocolatey package that you could recommend for this?

**Comment by majkinetor** [comment]
You can try https://github.com/mitmproxy/mitmproxy

If it works for you, I can create a choco package.

**Comment by gep13** [comment]
@russcam ah, I see what you mean now 😄 

In addition to the above, you might want to give this a try: https://chocolatey.org/packages/Charles

**Comment by brunoyb** [comment]
@majkinetor Hey, this mitmproxy tool seems to be a good alternative to both Fiddler and Charles. I would like to try it! Can you please create a package for us? I can also create one if you don't want to maintain it yourself or here. Thank you!

**Comment by majkinetor** [comment]
I added the issue in my repository: https://github.com/majkinetor/au-packages/issues/68
I am not sure when tho.

**Comment by ferventcoder** [comment]
March 2017ish may have been the change over to collecting info - https://github.com/chocolatey/chocolatey-coreteampackages/issues/632
