### ISSUE TITLE
FEATURE REQUEST: rufus package - shim the exe please

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-coreteampackages#964]
The current rufus package just consists of the portable exe, license, and verification files.

It would be wonderful if it included a chocolateyinstall.ps1 with the end result of the rufus.exe being shimmed.

**Comment by AdmiringWorm** [comment]
> It would be wonderful if it included a chocolateyinstall.ps1 with the end result of the rufus.exe being shimmed.

All exes that are put inside the package directory are automatically shimmed by chocolatey, and with that there are no need to have a install script.
See the highlighted line from the chocolatey test environment mentioning that the file is shimmed:
https://gist.github.com/choco-bot/983e2b6e9a9697dd9119a31f76910189#file-install-txt-L139

Because this is already happening, I'm closing this request

**Comment by bcurran3** [comment]
I know that's the way it's SUPPOSED to work. For whatever reason, it didn't  create a shim for me. So I tested. Uninstalled. Re-installed. This time I got a shim. Yay!
