### ISSUE TITLE
(dropbox) Is failing to parse version and download the binary

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#969]
Currently both the dropbox and the dropbox_beta package folders are failing the update run, the former with an error of invalid version, and the later with an error that the download file couldn't be found.

I plan to have a look at both of these later this week, along with combining them to a single package with streams.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
Dropbox package failed with a `invalid version` because of the compare check not finding the version in the dropbox forum yet. The beta version had a error in the url being used to download the installer had been changed by Dropbox.
I have since fixed both these errors and merged them into a stream package. I will be submitting the PR soon.

**Comment by AdmiringWorm** [comment]
@RedBaron2 sounds good, however I do still plan to parse the url from the blog post itself.
But that is something I can do from a separate issue at a later date
